### PR TITLE
Migrate to Maven

### PR DESCRIPTION
**Pull request by zaibacu**
`mvn package` will now:

- Download all of the required libraries (no more copy/pasting in order to build it)
- Generates required stuff
- Compiles
- Packages into jar

Old ant `build.xml` is still there, because there are parts like site and documentation which are not yet covered by maven

### CODE REVIEW

**Comment by mwhite14850** [comment]
Hi Šarūnas Navickas 

Thanks for this suggestion!  This appears to be related to what Adam Leskis has been working on with making a Docker image for the build:

https://github.com/OpenCCG/openccg/issues/23

It would be helpful if you and Adam (also Dave Howcroft?) could comment on whether it would make sense to incorporate both of these suggestions or just one or the other, and if both, whether there are any conflicts to resolve or synergies to pursue.

Mike

**Comment by lpmi-13** [comment]
The migration to use maven is sensible in any case, and the docker build branch could easily be rebased to incorporate this after its merged in.

**Comment by zaibacu** [comment]
Yes, I think these two are independant. If anything, this should make Docker image creation easier since maven is quite easy to setup and dependencies are downloaded instead of copied manually

**Comment by dmhowcroft** [comment]
My initial impression is that this build process simplifies the work that @lpmi-13 did to create the Docker image, so I also agree it would make sense to incorporate this PR before doing that one.

**Comment by mwhite14850** [comment]
Ok, thanks all, went ahead with the merge!

**Comment by lpmi-13** [comment]
just a note that we may also want to update the installation documentation to incorporate the new maven process.

**Comment by mwhite14850** [comment]
It would be great if someone who is familiar with maven could add this!

**Pull request merged**
